In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [ ]:
print("A + B =\n", A + B)
print("A - B =\n", A - B)


A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]


In [ ]:
  print("A dot B =\n", A.dot(B))
  print("A @ B=\n",A @ B)

A dot B =
 [[19 22]
 [43 50]]
A @ B=
 [[19 22]
 [43 50]]


In [ ]:
print("Element-wise multiply:\n",A*B)

Element-wise multiply:
 [[ 5 12]
 [21 32]]


In [ ]:
print("Transpose of A:\n", A.T)


Transpose of A:
 [[1 3]
 [2 4]]


In [ ]:
I = np.eye(3)
print("Identity Matrix:\n", I)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Z = np.zeros((3,3))
O = np.ones((2,4))

print("Zero Matrix:\n", Z)
print("Ones Matrix:\n", O)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
R = np.random.randint(1, 10, (3,3))
print("Random Matrix:\n", R)


Random Matrix:
 [[1 4 3]
 [7 4 4]
 [8 1 4]]


In [ ]:
A = np.array([[4, 7],
              [2, 6]])

inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)


Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
x = np.arange(12)
M = x.reshape(3,4)
print("Reshaped Matrix:\n", M)


Reshaped Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
A = np.ones((2,2))
B = np.zeros((2,2))

print("Horizontal concat:\n", np.hstack((A, B)))
print("Vertical concat:\n", np.vstack((A, B)))


Horizontal concat:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
Vertical concat:
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [ ]:
M = np.arange(1,17).reshape(4,4)
print("Matrix:\n", M)

print("First row:", M[0])
print("First column:", M[:,0])
print("2x2 block:\n", M[1:3, 1:3])


Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row: [1 2 3 4]
First column: [ 1  5  9 13]
2x2 block:
 [[ 6  7]
 [10 11]]
